docs: README fix.
dart-lightning/lndart.clightning pull request #65
Opened 2022-07-15 18:35 UTC by swaptr

This PR will fix all README issues, once an for all :)

2022-07-15 18:39 UTC, swaptr commented
For the `Hacking Guide`, do I just refer to the `docs/dev/MAINTAINERS.mdx`

2022-07-16 08:55 UTC, vincenzopalazzo requested changes

2022-07-16 08:55 UTC, vincenzopalazzo commented on README.md
> +| clightning_rpc | A RPC wrapper around the core lightning API.                    | unreleased |
```suggestion
| clightning_rpc | A RPC wrapper around the core lightning API.                    | v0.0.1 |
```

:) https://pub.dev/packages/clightning_rpc

2022-07-16 08:55 UTC, vincenzopalazzo commented on README.md
> +| cln_common     | A package that provides common interface for the monorepo.      | unreleased |
```suggestion
| [cln_common](com/README.md)     | A package that provides common interface for the monorepo.      | unreleased |
```

2022-07-16 08:55 UTC, merged